FROM ubuntu:22.04 AS build

RUN apt update && \
        apt install build-essential python3-pip opencl-headers ocl-icd-opencl-dev pkg-config xxd -y libpthread-stubs0-dev && \
        rm -rf /var/cache/apt && \
        python3 -m pip install meson ninja
RUN ln -s /usr/lib/x86_64-linux-gnu/libpthread.so.0 /usr/lib/x86_64-linux-gnu/libpthread.so
COPY . /code
RUN mkdir /build
WORKDIR /code
RUN LDFLAGS='-lpthread -static-libgcc -static-libstdc++' meson /build/code --default-library static --buildtype=release
WORKDIR /build/code
RUN ninja
RUN mkdir /install
RUN DESTDIR=/install meson install

FROM scratch AS export-stage
COPY --from=build install/usr/local/bin/wart-miner .
